version: "3"
services:
  amqp:
    # Normally, we expect the `rabbitmq` image. The -management images come
    # with a set of management plugins installed and enabled by default. They
    # can be accessed through the web interface on port 15672. The credentials
    # are guest/guest.
    image: rabbitmq:3-management
    # RabbitMQ stores data based on what it calls the "Node Name", which
    # defaults to the hostname. We set this, so we can keep track of our data.
    hostname: amqp
    # We expose the ports here, so decoupled agents can be developed with more
    # ease.
    ports:
      - "5672:5672"    # amqp port
      - "15672:15672"  # management port
  discord-bot:
    env_file: ./.env
    build: ./discord-bot
    restart: always
  discord-parser:
    build: ./discord-parser
    restart: always
  http-receiver:
    build: ./http-receiver
    restart: always
    ports: 
      - "8080:80"
  twilio-parser:
    build: ./twilio-parser
    restart: always
